CREATE TABLE claims (
    id SERIAL PRIMARY KEY,
    PROPERTY_ID BIGINT,
    PROPERTY_TYPE TEXT,
    CASH_REPORTED NUMERIC(10, 2),
    SHARES_REPORTED NUMERIC(10, 2),
    NAME_OF_SECURITIES_REPORTED TEXT,
    NO_OF_OWNERS TEXT,
    OWNER_NAME TEXT,
    OWNER_STREET_1 TEXT,
    OWNER_STREET_2 TEXT,
    OWNER_STREET_3 TEXT,
    OWNER_CITY TEXT,
    OWNER_STATE CHAR(2),
    OWNER_ZIP VARCHAR(10),
    OWNER_COUNTRY_CODE CHAR(3),
    CURRENT_CASH_BALANCE NUMERIC(10, 2),
    HOLDER_NAME TEXT
);

-- Create index after importing all the data.
-- CREATE INDEX idx_property_id ON claims (PROPERTY_ID);
